@if(!kirikiriz)
//These functions are present only in a later version of kirikiri.
Array.shift = function()
{
    var pos = 0;
	var item = this[pos];
	erase(pos);
	return item;
};

Array.unshift = function(item)
{
	insert(0,item);
};

Array.pop = function()
{
    var pos = count-1;
    var item = this[pos];
    erase(pos);
    return item;
};

global.dmt = (msg*) { Debug.message(msg.join(", ")+": "+Scripts.getTraceString()); };
@endif
