
global.AnimationLayer_patch_hd_layer_original = AnimationLayer;
class AnimationLayer_patch_hd_layer_override extends AnimationLayer_patch_hd_layer_original
{
	function AnimationLayer_patch_hd_layer_override()
	{
		super.AnimationLayer(...);
	}

	function AnimationLayer()
	{
		AnimationLayer_patch_hd_layer_override(...);
	}

	/*タグハンドラ*/function wait(elm)
	{
		var storageToAdd = %["linebreak_a" => 32, "pagebreak_a" => 3];
		var storage = Anim_cellLayer.imageStorage;
		var mobileAdd = storageToAdd[storage] !== void? storageToAdd[storage] : 0;
		return +elm.time + (window.sflags.mobileBreakGlyphs? mobileAdd : 0);
	}
}
global.AnimationLayer = AnimationLayer_patch_hd_layer_override;
