
global.MessageLayer_patch_noop_on_graph_not_found_original = MessageLayer;
class MessageLayer_patch_noop_on_graph_not_found_override extends MessageLayer_patch_noop_on_graph_not_found_original
{
	function MessageLayer_patch_noop_on_graph_not_found_override()
	{
		super.MessageLayer(...);
	}

	function MessageLayer()
	{
		MessageLayer_patch_noop_on_graph_not_found_override(...);
	}

	function putGraph(storage, key, ischar)
	{
		if (!global.Storages.isExistentImage(storage))
		{
			return false;
		}
		return super.putGraph(...);
	}
}
global.MessageLayer = MessageLayer_patch_noop_on_graph_not_found_override;
