@if(!kirikiriz)
//These functions are present only in a later version of kirikiri.
global.Array.shift = function()
{
    var pos = 0;
	var item = this[pos];
	this.erase(pos);
	return item;
};

global.Array.unshift = function(item)
{
	this.insert(0,item);
};

global.Array.pop = function()
{
    var pos = count-1;
    var item = this[pos];
    this.erase(pos);
    return item;
};

global.dmt = (msg*) { global.Debug.message(msg.join(", ")+": "+global.Scripts.getTraceString()); };
@endif
