
Layer.initVectorParticle = function(){};
Layer.initRotateParticle = function(){};
Layer.initAccelRotateParticle = function(){};
Layer.initBlinkParticle = function(){};
Layer.uninitParticle = function(){};
Layer.updateParticle = function(){};
Layer.assignParticle = function(){};
Layer.initializedParticle = false;
Layer.particleImage = void;
Layer.setParticleBlinkMax = function(){};
Layer.setParticleBlinkTime = function(){};
Layer.setParticleBlinkCount = function(){};
