global.Smudge = function(param) {};

global.Blur = function(elm)
{
	var level = elm.level;
	elm.layer.doBoxBlur(level, level);
};

global.Lens = function(elm) {};
global.InitLens = function() {};
global.ReleaseLens = function() {};

global.Noise = function(param) {};

global.Contrast = function(param) {};

global.initHaze = function(p) {};

global.doHaze = function(param) {};

global.endHaze = function() {};

global.Stretch = function(param) {};

global.Vortex = function(param) {};
