
global.MessageLayer_patch_noop_on_graph_not_found_original = global.MessageLayer;
class MessageLayer_patch_noop_on_graph_not_found_override extends global.MessageLayer_patch_noop_on_graph_not_found_original
{
	function MessageLayer_patch_noop_on_graph_not_found_override()
	{
		super.MessageLayer(...);
	}

	function MessageLayer()
	{
		this.MessageLayer_patch_noop_on_graph_not_found_override(...);
	}

	function putGraph(storage, key, ischar)
	{
		if (!global.Storages.isExistentImage(storage))
		{
			if (typeof(this.lastCh) === "String")
			{
				this.lastCh = void;
			}
			return false;
		}
		return super.putGraph(...);
	}
}
global.MessageLayer = global.MessageLayer_patch_noop_on_graph_not_found_override;
