@if(HD_MODE)
// filter.dll

function Noise_patch_hd_plugins_override(param)
{
	param.layer.absoluteMode = true;
	global.Noise_patch_hd_plugins_original(param);
	param.layer.absoluteMode = false;
}
if (typeof(global.Noise) === "Object")
{
	global.Noise_patch_hd_plugins_original = Noise;
	global.Noise = Noise_patch_hd_plugins_override;
}

function Contrast_patch_hd_plugins_override(elm)
{
	elm.layer.absoluteMode = true;
	global.Contrast_patch_hd_plugins_original(elm);
	elm.layer.absoluteMode = false;
}
if (typeof(global.Contrast) === "Object")
{
	global.Contrast_patch_hd_plugins_original = Contrast;
	global.Contrast = Contrast_patch_hd_plugins_override;
}

function doHaze_patch_hd_plugins_override(elm)
{
	elm.src.absoluteMode = true;
	elm.dest.absoluteMode = true;
	global.doHaze_patch_hd_plugins_original(elm);
	elm.src.absoluteMode = false;
	elm.dest.absoluteMode = false;
}
if (typeof(global.doHaze) === "Object")
{
	global.doHaze_patch_hd_plugins_original = doHaze;
	global.doHaze = doHaze_patch_hd_plugins_override;
}

// slideopen.dll

function initSlideOpen_patch_hd_plugins_override(plugin)
{
	if (global.kag.wideScreen) return; // Plugin doesn't work in wide screen for some reason.

	plugin.src.absoluteMode = true;
	plugin.dest.absoluteMode = true;
	global.initSlideOpen_patch_hd_plugins_original(plugin);
	plugin.src.absoluteMode = false;
	plugin.dest.absoluteMode = false;
}
if (typeof(global.initSlideOpen) === "Object")
{
	global.initSlideOpen_patch_hd_plugins_original = initSlideOpen;
	global.initSlideOpen = initSlideOpen_patch_hd_plugins_override;
}

function drawSlideOpen_patch_hd_plugins_override()
{
	if (global.kag.wideScreen) return;
	return global.drawSlideOpen_patch_hd_plugins_original(...);
}
if (typeof(global.drawSlideOpen) === "Object")
{
	global.drawSlideOpen_patch_hd_plugins_original = drawSlideOpen;
	global.drawSlideOpen = drawSlideOpen_patch_hd_plugins_override;
}

function finishSlideOpen_patch_hd_plugins_override()
{
	if (global.kag.wideScreen) return;
	return global.finishSlideOpen_patch_hd_plugins_original(...);
}
if (typeof(global.finishSlideOpen) === "Object")
{
	global.finishSlideOpen_patch_hd_plugins_original = finishSlideOpen;
	global.finishSlideOpen = finishSlideOpen_patch_hd_plugins_override;
}

// drawer.dll

function drawLine_patch_hd_plugins_override(layer, x0, y0, cx, cy, lc)
{
	var widthScale = layer.widthScale;
	var heightScale = layer.heightScale;
	layer.absoluteMode = true;
	global.drawLine_patch_hd_plugins_original(layer, x0*widthScale, y0*heightScale, cx*widthScale, cy*heightScale, lc);
	layer.absoluteMode = false;
}
if (typeof(global.drawLine) === "Object")
{
	global.drawLine_patch_hd_plugins_original = drawLine;
	global.drawLine = drawLine_patch_hd_plugins_override;
}


function drawAALine_patch_hd_plugins_override(layer, x0, y0, cx, cy, lc)
{
	var widthScale = layer.widthScale;
	var heightScale = layer.heightScale;
	layer.absoluteMode = true;
	global.drawAALine_patch_hd_plugins_original(layer, x0*widthScale, y0*heightScale, cx*widthScale, cy*heightScale, lc);
	layer.absoluteMode = false;
}
if (typeof(global.drawAALine) === "Object")
{
	global.drawAALine_patch_hd_plugins_original = drawAALine;
	global.drawAALine = drawAALine_patch_hd_plugins_override;
}

@endif
