// Kirikiroid support
var kirikiroidOsNames = ["android", "iphone", "ipad"];

function checkIfKirikiroid() {
	for (var i = 0, internal_forloop_count = kirikiroidOsNames.count; i < internal_forloop_count; i += 1) {
		if (System.osName.substr(0, kirikiroidOsNames[i].length).toLowerCase() == kirikiroidOsNames[i]) {
			return true;
		}
	}
	return false;
}

var isKirikiroid = checkIfKirikiroid();
if (isKirikiroid) {
	Scripts.eval("@set(KIRIKIROID=1)");
}
