
global.KAGWindow_patch_italictag_original = KAGWindow;
class KAGWindow_patch_italictag_override extends KAGWindow_patch_italictag_original
{
	function KAGWindow_patch_italictag_override()
	{
		super.KAGWindow(...);

		{
			var macros = this.mainConductor.macros;
			macros["italic"] = "[font italic][macropop]";
			macros["i"] = "[font italic][macropop]";
			macros["/i"] = "[font italic=0][macropop]";
		}
	}

	function KAGWindow()
	{
		KAGWindow_patch_italictag_override(...);
	}
}
global.KAGWindow = KAGWindow_patch_italictag_override;
