@call target=*tladata
*page0|
;バックログ画面[l]
;バックログのテキスト範囲はゲーム中と同じくらいにしてください。
;もしスクロールバーの位置をずらす場合は○系ボタンも同時に動かしてください。
;スクロールの移動位置と移動範囲は「x910/y71」～「x910/y462」です。
@r
@playtimeline scene=5
;出現
@l
@r
@playtimeline scene=6
;消滅
@r
@r
@r
@r
@r

@return
*tladata
@iscript
global.__tmp_tla = Scripts.eval('(const) %[
 "baseHeight" => 576,
 "baseWidth" => 1024,
 "cacheType" => "none",
 "currentSceneID" => 6,
 "objectSerial" => 72,
 "projectName" => "魔法使いの夜",
 "sceneSerial" => 7,
 "scenes" => (const) [
  5,
  (const) [
   (const) [
    (const) %[
     "childAbsolute" => 1000,
     "className" => "PageObject",
     "name" => "ページ",
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        1,
        0,
        1,
        null,
        null
       ],
       (const) [
        11,
        null,
        0,
        null,
        null,
        null,
        null
       ]
      ],
      12
     ],
     "uuid" => 34
    ],
    (const) %[
     "baseColor" => 4278242559,
     "childAbsolute" => 1000,
     "children" => (const) [
     ],
     "className" => "BGObject",
     "name" => "blue",
     "page" => 0,
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        0,
        0,
        1,
        null,
        null
       ]
      ],
      1
     ],
     "uuid" => 35
    ],
    (const) %[
     "baseColor" => 4294967295,
     "childAbsolute" => 2200,
     "children" => (const) [
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLback",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "mouseUp",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          0,
          0,
          1,
          "backlog_キャンセルボタン",
          921,
          548,
          2100,
          0,
          "0/0/27/28",
          null,
          3,
          null,
          null,
          null
         ],
         (const) [
          4,
          null,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          void,
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          null,
          546,
          null,
          255,
          null,
          "kag.hideHistory();release();",
          null,
          null,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 37
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLprev",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "mouseDown",
         "mouseUp",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          0,
          0,
          1,
          "backlog_矢印上ボタン",
          889,
          548,
          2000,
          0,
          "0/0/27/28",
          null,
          null,
          3,
          null,
          null,
          null
         ],
         (const) [
          3,
          null,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          void,
          null,
          null
         ],
         (const) [
          8,
          null,
          0,
          null,
          null,
          null,
          null,
          546,
          null,
          255,
          null,
          "BLonButtonDown(this);",
          "BLonButtonUp(this);",
          null,
          null,
          null,
          null
         ]
        ],
        9
       ],
       "uuid" => 38
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLnext",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "mouseDown",
         "mouseUp",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          0,
          0,
          1,
          "backlog_矢印下ボタン",
          857,
          548,
          1900,
          0,
          "0/0/27/28",
          null,
          null,
          3,
          null,
          null,
          null
         ],
         (const) [
          2,
          null,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          void,
          null,
          null
         ],
         (const) [
          7,
          null,
          0,
          null,
          null,
          null,
          null,
          546,
          null,
          255,
          null,
          "BLonButtonDown(this);",
          "BLonButtonUp(this);",
          null,
          null,
          null,
          null
         ]
        ],
        8
       ],
       "uuid" => 39
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLquickjump",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          0,
          0,
          1,
          "backlog_pgボタン",
          825,
          548,
          1800,
          0,
          "0/0/27/28",
          3,
          null,
          null,
          null
         ],
         (const) [
          1,
          null,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          void,
          null,
          null
         ],
         (const) [
          6,
          null,
          0,
          null,
          null,
          null,
          null,
          546,
          null,
          255,
          null,
          null,
          null,
          null,
          null
         ]
        ],
        7
       ],
       "uuid" => 40
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLスクロールスライダー",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega",
         "viewarea",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_カーソル",
          922,
          352,
          1700,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "0/0/24/56",
          null,
          null,
          null
         ],
         (const) [
          3,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          null,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          void,
          null,
          null
         ],
         (const) [
          11,
          null,
          0,
          null,
          null,
          null,
          922,
          352,
          1700,
          255,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 41
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLスクロールバー",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_カーソルバー",
          922,
          294,
          1600,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          3,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          null,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          11,
          null,
          0,
          null,
          null,
          null,
          922,
          294,
          1600,
          255,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 42
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLキャプション",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_title2",
          228,
          36,
          1500,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          4,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          null,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          11,
          null,
          0,
          null,
          null,
          null,
          238,
          36,
          1500,
          255,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 43
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLタイトル",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_title",
          66,
          36,
          1400,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          3,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          null,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          11,
          null,
          0,
          null,
          null,
          null,
          76,
          36,
          1400,
          255,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 44
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL草3",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "c_kusa3",
          95,
          33,
          1300,
          0,
          null,
          null,
          null,
          80,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          2,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          null,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          11,
          null,
          0,
          null,
          null,
          null,
          143,
          33,
          1300,
          255,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 45
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL草2",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          7,
          1,
          "system_kusa2",
          946,
          425,
          1200,
          0,
          null,
          null,
          null,
          null,
          52.431,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          2,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          null,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          11,
          null,
          0,
          0,
          null,
          null,
          946,
          288,
          1200,
          255,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 46
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL草1",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          7,
          1,
          "system_kusa1",
          928,
          53,
          1100,
          0,
          null,
          null,
          null,
          56.772,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          2,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          null,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          11,
          null,
          0,
          0,
          null,
          null,
          850,
          53,
          1100,
          255,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 47
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL背景",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "opacity"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "system_background",
          512,
          288,
          0,
          null,
          null
         ],
         (const) [
          11,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          255,
          null,
          null
         ]
        ],
        12
       ],
       "uuid" => 48
      ]
     ],
     "className" => "BGObject",
     "name" => "white",
     "page" => 1,
     "timeline" => (const) [
      (const) [
       "storage",
       "left",
       "top"
      ],
      (const) [
       (const) [
        0,
        0,
        1,
        0,
        1,
        "black",
        -48,
        -48,
        null,
        null
       ],
       (const) [
        11,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ],
      12
     ],
     "uuid" => 36
    ],
    (const) %[
     "className" => "MenuObject",
     "name" => "menu5",
     "pluginName" => "menu",
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        0,
        0,
        1,
        null,
        null
       ]
      ],
      1
     ],
     "uuid" => 49
    ],
    (const) %[
     "className" => "BGMObject",
     "name" => "BGM",
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        0,
        0,
        1,
        null,
        null
       ]
      ],
      1
     ],
     "uuid" => 50
    ]
   ],
   void,
   20,
   0,
   "",
   void,
   void,
   0,
   1,
   16,
   44,
   1309832879000,
   0,
   0,
   0,
   (const) [
   ],
   (const) [
   ]
  ],
  6,
  (const) [
   (const) [
    (const) %[
     "childAbsolute" => 1000,
     "className" => "PageObject",
     "name" => "ページ",
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        1,
        0,
        1,
        null,
        null
       ],
       (const) [
        9,
        null,
        0,
        null,
        null,
        null,
        null
       ]
      ],
      10
     ],
     "uuid" => 55
    ],
    (const) %[
     "baseColor" => 4278242559,
     "childAbsolute" => 1000,
     "children" => (const) [
     ],
     "className" => "BGObject",
     "name" => "blue",
     "page" => 0,
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        0,
        0,
        1,
        null,
        null
       ]
      ],
      1
     ],
     "uuid" => 56
    ],
    (const) %[
     "baseColor" => 4294967295,
     "childAbsolute" => 2200,
     "children" => (const) [
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLback",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_キャンセルボタン",
          921,
          546,
          2100,
          null,
          "0/0/27/28",
          3,
          null,
          null,
          null
         ],
         (const) [
          6,
          null,
          0,
          null,
          null,
          null,
          922,
          566,
          null,
          0,
          null,
          null,
          void,
          null,
          null
         ]
        ],
        7
       ],
       "uuid" => 58
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLprev",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          0,
          0,
          1,
          "backlog_矢印上ボタン",
          889,
          546,
          2000,
          null,
          "0/0/27/28",
          3,
          null,
          null,
          null
         ],
         (const) [
          1,
          null,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          void,
          null,
          null
         ],
         (const) [
          7,
          null,
          0,
          null,
          null,
          null,
          null,
          566,
          null,
          0,
          null,
          null,
          null,
          null,
          null
         ]
        ],
        8
       ],
       "uuid" => 59
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLnext",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          0,
          0,
          1,
          "backlog_矢印下ボタン",
          857,
          546,
          1900,
          null,
          "0/0/27/28",
          3,
          null,
          null,
          null
         ],
         (const) [
          2,
          null,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          void,
          null,
          null
         ],
         (const) [
          8,
          null,
          0,
          null,
          null,
          null,
          null,
          566,
          null,
          0,
          null,
          null,
          null,
          null,
          null
         ]
        ],
        9
       ],
       "uuid" => 60
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLquickjump",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "viewarea",
         "itemMode",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          0,
          0,
          1,
          "backlog_pgボタン",
          825,
          546,
          1800,
          null,
          "0/0/27/28",
          3,
          null,
          null,
          null
         ],
         (const) [
          3,
          null,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          void,
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          null,
          563,
          null,
          0,
          null,
          null,
          null,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 61
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLスクロールスライダー",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega",
         "viewarea",
         "viewareaNo"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_カーソル",
          922,
          352,
          1700,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "0/0/24/56",
          null,
          null,
          null
         ],
         (const) [
          7,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          0,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          void,
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          922,
          352,
          1700,
          null,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 62
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLスクロールバー",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_カーソルバー",
          922,
          294,
          1600,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          7,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          0,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          922,
          294,
          1600,
          null,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 63
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLキャプション",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_title2",
          238,
          36,
          1500,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          7,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          0,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          238,
          56,
          1500,
          null,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 64
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BLタイトル",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity",
         "afx",
         "afy",
         "rotate",
         "zoomx",
         "zoomy",
         "quakeHMax",
         "quakeVMax",
         "quakeInterval",
         "shakeHMax",
         "shakeVMax",
         "shakeCycle",
         "swingMinCycle",
         "swingMaxCycle",
         "swingMinVibration",
         "swingMaxVibration",
         "swingRate",
         "hazePower",
         "hazeDelta",
         "hazeOmega"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "backlog_title",
          76,
          36,
          1400,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null
         ],
         (const) [
          7,
          null,
          null,
          null,
          null,
          null,
          "~",
          "~",
          "~",
          0,
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          "~",
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          76,
          51,
          1400,
          null,
          -100000,
          -100000,
          0,
          100,
          100,
          10,
          10,
          50,
          0,
          10,
          300,
          1000,
          2000,
          5,
          10,
          1,
          10,
          7,
          1,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 65
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL草3",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "c_kusa3",
          143,
          33,
          1300,
          null,
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 66
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL草2",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "system_kusa2",
          946,
          288,
          1200,
          null,
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 67
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL草1",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "absolute",
         "opacity"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "system_kusa1",
          850,
          53,
          1100,
          null,
          null,
          null
         ],
         (const) [
          9,
          null,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 68
      ],
      (const) %[
       "className" => "MenuItemObject",
       "earth" => 0,
       "name" => "BL背景",
       "timeline" => (const) [
        (const) [
         "storage",
         "center",
         "vcenter",
         "opacity"
        ],
        (const) [
         (const) [
          0,
          0,
          1,
          0,
          1,
          "system_background",
          512,
          288,
          null,
          null,
          null
         ],
         (const) [
          9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          null,
          null
         ]
        ],
        10
       ],
       "uuid" => 69
      ]
     ],
     "className" => "BGObject",
     "name" => "white",
     "page" => 1,
     "timeline" => (const) [
      (const) [
       "storage",
       "left",
       "top"
      ],
      (const) [
       (const) [
        0,
        0,
        1,
        0,
        1,
        "black",
        -48,
        -48,
        null,
        null
       ],
       (const) [
        9,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ],
      10
     ],
     "uuid" => 57
    ],
    (const) %[
     "className" => "MenuObject",
     "name" => "menu5",
     "pluginName" => "menu",
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        0,
        0,
        1,
        null,
        null
       ]
      ],
      1
     ],
     "uuid" => 70
    ],
    (const) %[
     "className" => "BGMObject",
     "name" => "BGM",
     "timeline" => (const) [
      (const) [
      ],
      (const) [
       (const) [
        0,
        0,
        0,
        0,
        1,
        null,
        null
       ]
      ],
      1
     ],
     "uuid" => 71
    ]
   ],
   void,
   20,
   0,
   "",
   void,
   void,
   0,
   1,
   12,
   65,
   1332209754000,
   0,
   0,
   0,
   (const) [
   ],
   (const) [
   ]
  ]
 ],
 "version" => 1
]');
global.__tla_name = "backlog";

@endscript
@eval exp=timeline_object.loadByData(global.__tmp_tla,global.__tla_name)
@return
