(const) %[
 "projectName" => "魔法使いの夜",
 "nextFrames" => (const) [
  void,
  void,
  void,
  void,
  void
 ],
 "cacheType" => "none",
 "textStorage" => "file://./d/witchontheholynight/vol.1/data/scenario/dummy_gamemenu.ks",
 "objects" => (const) [
  (const) %[
   "objectSelected" => 0,
   "className" => "PageObject",
   "visible" => 1,
   "lock" => void,
   "name" => "ページ",
   "outlineColor" => 4294922239,
   "children" => void,
   "outline" => void,
   "uuid" => "2a97381e-10d3-4bf1-b7bd-254511d2ed38",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
    ],
    "length" => 42,
    "frames" => (const) [
     (const) [
      0,
      0,
      0,
      0,
      "linear",
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 1,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像1",
   "outlineColor" => 4288230348,
   "children" => void,
   "outline" => void,
   "uuid" => "1e4521ff-0d88-420f-94ca-12a8557428d1",
   "choseFrame" => (const) [
    (const) %[
     "ed" => 0,
     "st" => 0
    ]
   ],
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      0,
      1,
      1,
      "linear",
      "black",
      -0x1.9000000000000p5 /* -50 */,
      -0x1.9000000000000p5 /* -50 */,
      20000,
      0,
      null
     ],
     (const) [
      20,
      null,
      0,
      0,
      null,
      null,
      null,
      null,
      null,
      160,
      null
     ],
     (const) [
      21,
      null,
      1,
      6,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      41,
      null,
      0,
      0,
      null,
      null,
      null,
      null,
      null,
      0,
      null
     ],
     (const) [
      43,
      null,
      1,
      6,
      null,
      null,
      null,
      null,
      null,
      160,
      null
     ],
     (const) [
      53,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      0,
      null
     ],
     (const) [
      54,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      160,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像2",
   "outlineColor" => 4283432783,
   "children" => void,
   "outline" => void,
   "uuid" => "1cb872e7-0710-4811-890f-fbc45fa4f846",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea",
     "mouseUp",
     "itemMode"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_graphic",
      0x1.B080000000000p9 /* 865 */,
      0x1.4000000000000p3 /* 10 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null,
      null,
      null
     ],
     (const) [
      10,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.7000000000000p4 /* 23 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      12,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.4000000000000p3 /* 10 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      43,
      1,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "void",
      0,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      -0x1.0000000000000p2 /* -4 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null,
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.4000000000000p3 /* 10 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      43,
      1,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像3",
   "outlineColor" => 4294922063,
   "children" => void,
   "outline" => void,
   "uuid" => "cd4961ed-2ab3-4869-8630-cb5b4d5fafdf",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_save",
      0x1.B080000000000p9 /* 865 */,
      0x1.AA00000000000p5 /* 53.25 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null
     ],
     (const) [
      11,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.0900000000000p6 /* 66.25 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      13,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.AA00000000000p5 /* 53.25 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.3A00000000000p5 /* 39.25 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.AA00000000000p5 /* 53.25 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像4",
   "outlineColor" => 4283400447,
   "children" => void,
   "outline" => void,
   "uuid" => "495d48d1-5507-431f-a6a2-7f8c22eb2a60",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_autoread",
      0x1.B080000000000p9 /* 865 */,
      0x1.8200000000000p6 /* 96.5 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null
     ],
     (const) [
      12,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.B600000000000p6 /* 109.5 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      14,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.8200000000000p6 /* 96.5 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.4A00000000000p6 /* 82.5 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.8200000000000p6 /* 96.5 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像5",
   "outlineColor" => 4283432959,
   "children" => void,
   "outline" => void,
   "uuid" => "38dd6ae5-3dd9-4a9d-a436-c24f665ed37a",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_load",
      0x1.B080000000000p9 /* 865 */,
      0x1.1780000000000p7 /* 139.75 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null
     ],
     (const) [
      13,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.3180000000000p7 /* 152.75 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      15,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.1780000000000p7 /* 139.75 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.F700000000000p6 /* 125.75 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.1780000000000p7 /* 139.75 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像6",
   "outlineColor" => 4294922239,
   "children" => void,
   "outline" => void,
   "uuid" => "aa436a29-900c-4bcb-8f53-7e9aa7fa4ed9",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea",
     "mouseUp",
     "itemMode"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_exitmenu",
      0x1.B080000000000p9 /* 865 */,
      0x1.6E00000000000p7 /* 183 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null,
      null,
      null
     ],
     (const) [
      14,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.8800000000000p7 /* 196 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      16,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.6E00000000000p7 /* 183 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      21,
      1,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      0,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.5200000000000p7 /* 169 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null,
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.6E00000000000p7 /* 183 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null,
      1,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像7",
   "outlineColor" => 4294967119,
   "children" => void,
   "outline" => void,
   "uuid" => "1044e894-e853-4f5e-8735-9fca4fe92473",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_history",
      0x1.B080000000000p9 /* 865 */,
      0x1.C480000000000p7 /* 226.25 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null
     ],
     (const) [
      15,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.DE80000000000p7 /* 239.25 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      17,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.C480000000000p7 /* 226.25 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.A880000000000p7 /* 212.25 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.C480000000000p7 /* 226.25 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像8",
   "outlineColor" => 4288230348,
   "children" => void,
   "outline" => void,
   "uuid" => "37ba0372-5e4e-46bc-9918-4126cc802e89",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_exitgame",
      0x1.B080000000000p9 /* 865 */,
      0x1.0D80000000000p8 /* 269.5 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null
     ],
     (const) [
      16,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.1A80000000000p8 /* 282.5 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      18,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.0D80000000000p8 /* 269.5 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.FF00000000000p7 /* 255.5 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.0D80000000000p8 /* 269.5 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像9",
   "outlineColor" => 4294922239,
   "children" => void,
   "outline" => void,
   "uuid" => "30ab22ba-971c-400d-add2-ba8d68e9eebe",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_config",
      0x1.B080000000000p9 /* 865 */,
      0x1.38C0000000000p8 /* 312.75 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null
     ],
     (const) [
      17,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.45C0000000000p8 /* 325.75 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      19,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.38C0000000000p8 /* 312.75 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.2AC0000000000p8 /* 298.75 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.38C0000000000p8 /* 312.75 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuItemObject",
   "visible" => 1,
   "lock" => void,
   "name" => "画像10",
   "outlineColor" => 4294967119,
   "children" => void,
   "outline" => void,
   "uuid" => "e0f51753-d5ed-4a27-895b-4e6210a80fe5",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "absolute",
     "opacity",
     "afx",
     "afy",
     "rotate",
     "zoomx",
     "zoomy",
     "quakeHMax",
     "quakeVMax",
     "quakeInterval",
     "shakeHMax",
     "shakeVMax",
     "shakeCycle",
     "hazePower",
     "hazeDelta",
     "hazeOmega",
     "viewarea"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      "m_returntop",
      0x1.B080000000000p9 /* 865 */,
      0x1.6300000000000p8 /* 355 */,
      25000,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "0/0/149/31",
      null
     ],
     (const) [
      18,
      0,
      1,
      2,
      null,
      null,
      null,
      0x1.7000000000000p8 /* 368 */,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      20,
      null,
      0,
      0,
      null,
      null,
      null,
      0x1.6300000000000p8 /* 355 */,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      21,
      null,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      31,
      null,
      0,
      null,
      null,
      null,
      0x1.C300000000000p9 /* 902 */,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      43,
      null,
      1,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      null,
      null,
      255,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      null,
      null,
      0x1.5500000000000p8 /* 341 */,
      null,
      0,
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      "~",
      null,
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      null,
      "~",
      "~",
      null,
      "~",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      64,
      null,
      null,
      null,
      null,
      null,
      0x1.B080000000000p9 /* 865 */,
      0x1.6300000000000p8 /* 355 */,
      null,
      255,
      -100000,
      -100000,
      0,
      100,
      100,
      10,
      10,
      50,
      0,
      10,
      300,
      10,
      7,
      1,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "BGObject",
   "visible" => 1,
   "page" => 0,
   "lock" => void,
   "baseColor" => 4278242559,
   "name" => "blue",
   "outlineColor" => 4283432959,
   "children" => (const) [
   ],
   "outline" => void,
   "uuid" => "2c98e765-17c9-4f9c-83a1-cf68ece92a6d",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "usecurrent"
    ],
    "length" => 42,
    "frames" => (const) [
     (const) [
      0,
      0,
      0,
      0,
      "linear",
      "o冬樹大橋の上(行き)-(昼)",
      -0x1.8000000000000p5 /* -48 */,
      -0x1.8000000000000p5 /* -48 */,
      1,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "BGObject",
   "visible" => 1,
   "page" => 1,
   "lock" => void,
   "baseColor" => 4294967295,
   "name" => "white",
   "outlineColor" => 4283400447,
   "children" => (const) [
   ],
   "outline" => void,
   "uuid" => "0d31caab-79db-49e7-ba89-0f194eec886e",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "usecurrent"
    ],
    "length" => 42,
    "frames" => (const) [
     (const) [
      0,
      0,
      0,
      0,
      "linear",
      "o冬木大橋袂の公園1(秋)-(昼)",
      -0x1.8000000000000p5 /* -48 */,
      -0x1.8000000000000p5 /* -48 */,
      1,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "BGMObject",
   "visible" => 1,
   "lock" => void,
   "name" => "BGM",
   "outlineColor" => 4294922063,
   "children" => void,
   "outline" => void,
   "uuid" => "137333f5-933c-45f9-ba63-8691eab2003e",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
    ],
    "length" => 42,
    "frames" => (const) [
     (const) [
      0,
      0,
      0,
      0,
      "linear",
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuObject",
   "pluginName" => "menu",
   "visible" => 1,
   "lock" => void,
   "name" => "menu",
   "outlineColor" => 4283432783,
   "children" => void,
   "outline" => void,
   "uuid" => "4e4e598b-3222-458c-95e8-c975be614e51",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "lclick",
     "rclick",
     "script"
    ],
    "length" => 65,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      null,
      null,
      null,
      null
     ],
     (const) [
      42,
      0,
      null,
      null,
      null,
      null,
      null,
      "finish();\r\\nkag.process(\"gamemenu.ks\",\"*return\");\r\n",
      null
     ],
     (const) [
      43,
      null,
      null,
      null,
      null,
      null,
      null,
      "void",
      null
     ],
     (const) [
      53,
      null,
      null,
      null,
      null,
      54,
      54,
      "void",
      null
     ],
     (const) [
      54,
      null,
      null,
      null,
      null,
      "void",
      21,
      "void",
      null
     ]
    ]
   ]
  ]
 ],
 "baseHeight" => 576,
 "timelineType" => "acting",
 "currentSelectedObjectUUID" => "1e4521ff-0d88-420f-94ca-12a8557428d1",
 "beginFrames" => (const) [
  0,
  21,
  43,
  54,
  65
 ],
 "currentAbsolute" => 2000,
 "baseWidth" => 1024,
 "frameRate" => 50
]