(const) %[
 "projectName" => "FatePS2",
 "nextFrames" => (const) [
  void,
  void,
  void,
  void,
  void,
  void,
  void,
  void
 ],
 "cacheType" => "none",
 "textStorage" => "menutest.ks",
 "objects" => (const) [
  (const) %[
   "objectSelected" => 0,
   "className" => "PageObject",
   "visible" => 1,
   "lock" => void,
   "name" => "ページ",
   "outlineColor" => 4288230348,
   "children" => void,
   "outline" => void,
   "uuid" => "c8521053-bf47-4ef5-9c9b-b08142e2da98",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "page"
    ],
    "length" => 238,
    "frames" => (const) [
     (const) [
      0,
      0,
      1,
      0,
      "linear",
      null,
      null
     ],
     (const) [
      20,
      null,
      0,
      null,
      null,
      0,
      null
     ],
     (const) [
      100,
      null,
      1,
      null,
      null,
      null,
      null
     ],
     (const) [
      116,
      null,
      0,
      null,
      null,
      1,
      null
     ],
     (const) [
      171,
      null,
      null,
      null,
      null,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "BGObject",
   "visible" => 1,
   "page" => 0,
   "lock" => void,
   "baseColor" => 4278242559,
   "name" => "blue",
   "outlineColor" => 4294967119,
   "children" => (const) [
   ],
   "outline" => void,
   "uuid" => "2cb8d3ed-cd6d-4f53-a6ee-585501db3da3",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "zoomx"
    ],
    "length" => 161,
    "frames" => (const) [
     (const) [
      0,
      0,
      0,
      0,
      "linear",
      "t_caution",
      0x1.C000000000000p6 /* 112 */,
      -0x1.8000000000000p3 /* -12 */,
      0x1.0068F5C28F5C3p7 /* 128.205 */,
      null
     ],
     (const) [
      171,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "BGObject",
   "visible" => 1,
   "page" => 1,
   "lock" => void,
   "baseColor" => 4294967295,
   "name" => "white",
   "outlineColor" => 4294922239,
   "children" => (const) [
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294922063,
     "children" => void,
     "outline" => void,
     "uuid" => "563d3325-c954-4b2c-9696-0621470a4a24",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "zoomx"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_fatelogo",
        1600,
        null,
        null,
        null
       ],
       (const) [
        108,
        0,
        1,
        "",
        null,
        -0x1.4000000000000p4 /* -20 */,
        0x1.3000000000000p5 /* 38 */,
        null,
        null,
        0,
        null,
        null
       ],
       (const) [
        124,
        null,
        0,
        0,
        null,
        0,
        null,
        null,
        null,
        255,
        null,
        null
       ],
       (const) [
        144,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        145,
        0,
        1,
        null,
        null,
        0x1.E800000000000p7 /* 244 */,
        0x1.7D00000000000p8 /* 381 */,
        "ex_title",
        null,
        0,
        null,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        -0x1.0000000000000p0 /* -1 */,
        0x1.0000000000000p1 /* 2 */,
        "sp_bg",
        1000,
        0,
        0x1.0080000000000p7 /* 128.25 */,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283400447,
     "children" => void,
     "outline" => void,
     "uuid" => "71d44331-4662-4c18-805f-71afb44d42be",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity"
      ],
      "length" => 224,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_halogo",
        1500,
        null,
        null
       ],
       (const) [
        112,
        0,
        1,
        7,
        null,
        -0x1.E000000000000p4 /* -30 */,
        0x1.7800000000000p7 /* 188 */,
        null,
        1600,
        0,
        null
       ],
       (const) [
        128,
        null,
        0,
        0,
        null,
        -0x1.9000000000000p5 /* -50 */,
        null,
        null,
        1500,
        255,
        null
       ],
       (const) [
        144,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        145,
        0,
        1,
        null,
        null,
        0,
        0x1.BE00000000000p8 /* 446 */,
        "ex_bar",
        null,
        0,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        null,
        0x1.F000000000000p8 /* 496 */,
        null,
        null,
        255,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        -0x1.5400000000000p6 /* -85 */,
        0x1.8000000000000p4 /* 24 */,
        "sp_title",
        null,
        0,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283432959,
     "children" => void,
     "outline" => void,
     "uuid" => "ac87b787-2028-4179-b0a5-8da1c248e39f",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "rotate",
       "zoomx",
       "zoomy",
       "viewarea",
       "mouseDown",
       "mouseUp",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_fraga",
        1400,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        108,
        0,
        1,
        10,
        null,
        -0x1.4000000000000p4 /* -20 */,
        0x1.AA00000000000p7 /* 213 */,
        null,
        1000,
        null,
        0x1.6800000000000p5 /* 45 */,
        0x1.EE570A3D70A3Dp7 /* 247.17 */,
        0x1.4353F7CED9168p0 /* 1.263 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        132,
        null,
        0,
        0,
        null,
        null,
        null,
        null,
        1400,
        null,
        null,
        0x1.9000000000000p6 /* 100 */,
        0x1.9000000000000p6 /* 100 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        144,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        100,
        100,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        145,
        0,
        1,
        null,
        null,
        0x1.D800000000000p6 /* 118 */,
        0x1.C900000000000p8 /* 457 */,
        "ex_gallery",
        null,
        0,
        0,
        null,
        null,
        "0/0/105/36",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        0x1.6000000000000p6 /* 88 */,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        "void",
        "nextFrame=171",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "void",
        null,
        null,
        0,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        "nextFrame=171",
        null,
        null,
        1,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.DC00000000000p7 /* 238 */,
        0x1.6000000000000p5 /* 44 */,
        "gl_bar-2",
        null,
        0,
        null,
        0x1.0400000000000p7 /* 130 */,
        null,
        "void",
        null,
        "void",
        null,
        null,
        0,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294922239,
     "children" => void,
     "outline" => void,
     "uuid" => "ad6a94d9-b0b0-4e02-901a-d8b35e6a5ab0",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_kanalogo",
        1300,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        120,
        0,
        1,
        null,
        null,
        -0x1.4000000000000p3 /* -10 */,
        0x1.4C00000000000p8 /* 332 */,
        null,
        1600,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        136,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        1500,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        144,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        145,
        0,
        1,
        null,
        null,
        0x1.1600000000000p8 /* 278 */,
        0x1.C900000000000p8 /* 457 */,
        "ex_music",
        null,
        0,
        "0/0/92/31",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        0x1.0200000000000p8 /* 258 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        -0x1.BC00000000000p6 /* -111 */,
        0x1.2000000000000p5 /* 36 */,
        "sp_花札",
        null,
        0,
        "0/0/393/319",
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294967119,
     "children" => void,
     "outline" => void,
     "uuid" => "47c20440-424d-4bd4-8d4e-e434a2c671f9",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        0,
        0,
        0,
        "linear",
        null,
        null,
        "void",
        2600,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        144,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        145,
        0,
        1,
        null,
        null,
        0x1.C600000000000p8 /* 454 */,
        0x1.C900000000000p8 /* 457 */,
        "ex_movie",
        null,
        0,
        "0/0/95/31",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        0x1.DA00000000000p8 /* 474 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.5000000000000p4 /* 21 */,
        0x1.1100000000000p8 /* 273 */,
        "sp_イリヤ城",
        null,
        0,
        "0/0/395/320",
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4288230348,
     "children" => void,
     "outline" => void,
     "uuid" => "bd64d52f-37c2-4e5f-8f19-70150387290c",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        0,
        0,
        0,
        "linear",
        null,
        null,
        "void",
        2500,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        144,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        145,
        0,
        1,
        null,
        null,
        0x1.3280000000000p9 /* 613 */,
        0x1.C900000000000p8 /* 457 */,
        "ex_scene",
        null,
        0,
        "0/0/87/31",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        0x1.4180000000000p9 /* 643 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.D000000000000p4 /* 29 */,
        -0x1.0000000000000p4 /* -16 */,
        "sp_劇場版",
        3000,
        0,
        "0/0/718/628",
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        2500,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283432959,
     "children" => void,
     "outline" => void,
     "uuid" => "9639e21e-4443-464f-8655-32fa243dcd45",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "void",
        2800,
        null,
        null,
        null,
        null
       ],
       (const) [
        197,
        0,
        1,
        null,
        null,
        0x1.2200000000000p8 /* 290 */,
        0x1.4000000000000p5 /* 40 */,
        "sp_遠坂神社",
        null,
        0,
        "0/0/388/315",
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        1,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 1,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283400447,
     "children" => void,
     "outline" => void,
     "uuid" => "a32e7900-7102-4c00-9978-0f1ec49c8f02",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "void",
        2900,
        null,
        null,
        null,
        null
       ],
       (const) [
        197,
        0,
        1,
        null,
        null,
        0x1.D200000000000p8 /* 466 */,
        0x1.FE00000000000p7 /* 255 */,
        "sp_壁紙",
        null,
        0,
        "0/0/386/326",
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        1,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294922239,
     "children" => void,
     "outline" => void,
     "uuid" => "8f95711d-328f-4136-ba79-f25c9cf9d0e7",
     "choseFrame" => (const) [
      (const) %[
       "ed" => 183,
       "st" => 183
      ]
     ],
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseUp",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        0,
        0,
        0,
        "linear",
        null,
        null,
        "void",
        2700,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        144,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        145,
        0,
        1,
        null,
        null,
        0x1.9180000000000p9 /* 803 */,
        0x1.0C80000000000p9 /* 537 */,
        "ex_back",
        null,
        0,
        "0/0/91/36",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        "void",
        "nextFrame=158",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "void",
        null,
        null,
        0,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        171,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        158,
        null,
        null,
        null,
        null
       ],
       (const) [
        183,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        184,
        null,
        null,
        1,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        158,
        null,
        null,
        0,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "nextFrame=158",
        null,
        null,
        1,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        null,
        null,
        "sp_back",
        null,
        0,
        null,
        null,
        158,
        null,
        null,
        0,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        210,
        null,
        null,
        1,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        158,
        null,
        null,
        0,
        null
       ],
       (const) [
        222,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294967119,
     "children" => void,
     "outline" => void,
     "uuid" => "0853ee5c-3973-44a0-857b-9a21f0d8a0fa",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_typemoon",
        1200,
        null,
        null,
        null
       ],
       (const) [
        126,
        0,
        1,
        null,
        null,
        0x1.0700000000000p8 /* 263 */,
        0x1.1E00000000000p9 /* 572 */,
        null,
        null,
        0,
        null,
        null
       ],
       (const) [
        138,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null
       ],
       (const) [
        145,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        171,
        0,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        1,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        0,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4288230348,
     "children" => void,
     "outline" => void,
     "uuid" => "83f46bf6-ca11-40ce-a7e1-5a70186113ec",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_title",
        1100,
        null,
        null
       ],
       (const) [
        132,
        0,
        1,
        null,
        null,
        -0x1.D800000000000p5 /* -59 */,
        0x1.D000000000000p4 /* 29 */,
        null,
        1700,
        0,
        null
       ],
       (const) [
        144,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        157,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        128,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        128,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        128,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4288230348,
     "children" => void,
     "outline" => void,
     "uuid" => "749da2f9-3c62-44e4-9d33-aa2feda9a8af",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "keyDown",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_start",
        1800,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        112,
        0,
        1,
        "",
        null,
        0x1.3600000000000p8 /* 310 */,
        0x1.7E00000000000p8 /* 382 */,
        null,
        null,
        0,
        "0/0/101/28",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        124,
        null,
        0,
        0,
        null,
        0x1.1800000000000p8 /* 280 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        "if(key==VK_UP&&(tmp=getMIfI(\"tl_quit\"))!=void){tmp.focus();result=true;}",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "void",
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.3600000000000p8 /* 310 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.1800000000000p8 /* 280 */,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        0x1.F000000000000p5 /* 62 */,
        0x1.B800000000000p6 /* 110 */,
        "gls_card",
        null,
        0,
        "0/0/245/407",
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "viewareaNo=0",
        null,
        0,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        "void",
        null,
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.1800000000000p8 /* 280 */,
        0x1.7E00000000000p8 /* 382 */,
        "tl_start",
        null,
        255,
        "0/0/101/28",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283432783,
     "children" => void,
     "outline" => void,
     "uuid" => "9f6f4480-26e3-4461-bcea-370966abc31d",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_continue",
        2400,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        114,
        0,
        1,
        "",
        null,
        0x1.5F00000000000p8 /* 351 */,
        0x1.A300000000000p8 /* 419 */,
        null,
        null,
        0,
        "0/0/161/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        127,
        null,
        0,
        0,
        null,
        0x1.4100000000000p8 /* 321 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.5F00000000000p8 /* 351 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.4100000000000p8 /* 321 */,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        0x1.5400000000000p6 /* 85 */,
        0x1.1000000000000p7 /* 136 */,
        "gls_hollowa",
        null,
        0,
        "void",
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.4100000000000p8 /* 321 */,
        0x1.A300000000000p8 /* 419 */,
        "tl_continue",
        null,
        255,
        "0/0/161/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294922063,
     "children" => void,
     "outline" => void,
     "uuid" => "fdce564c-1e7d-4b97-844a-0c8deb816178",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_config",
        2300,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        116,
        0,
        1,
        "",
        null,
        0x1.8F00000000000p8 /* 399 */,
        0x1.C800000000000p8 /* 456 */,
        null,
        null,
        0,
        "0/0/120/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        129,
        null,
        0,
        0,
        null,
        0x1.7100000000000p8 /* 369 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.8F00000000000p8 /* 399 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.7100000000000p8 /* 369 */,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        0x1.9800000000000p5 /* 51 */,
        0x1.0180000000000p9 /* 515 */,
        "gls_hollowbutton",
        null,
        0,
        "0/0/250/32",
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "viewareaNo=0",
        0,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        "void",
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.7100000000000p8 /* 369 */,
        0x1.C800000000000p8 /* 456 */,
        "tl_config",
        null,
        255,
        "0/0/120/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283400447,
     "children" => void,
     "outline" => void,
     "uuid" => "cd81b6f4-747b-4207-b5d5-2a1e25f91dae",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_eclipse",
        2200,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        118,
        0,
        1,
        "",
        null,
        0x1.BC00000000000p8 /* 444 */,
        0x1.EC00000000000p8 /* 492 */,
        null,
        null,
        0,
        "0/0/119/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        131,
        null,
        0,
        0,
        null,
        0x1.9E00000000000p8 /* 414 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.BC00000000000p8 /* 444 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.9E00000000000p8 /* 414 */,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        0x1.CC00000000000p8 /* 460 */,
        0x1.B800000000000p6 /* 110 */,
        "gls_card",
        null,
        0,
        "0/0/245/407",
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "viewareaNo=0",
        0,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        "void",
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.9E00000000000p8 /* 414 */,
        0x1.EC00000000000p8 /* 492 */,
        "tl_eclipse",
        null,
        255,
        "0/0/119/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283432959,
     "children" => void,
     "outline" => void,
     "uuid" => "b03d208c-eb7a-4951-a274-e84f4e32b4bf",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseUp",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_extra",
        2100,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        120,
        0,
        1,
        "",
        null,
        0x1.1700000000000p9 /* 558 */,
        0x1.7E00000000000p8 /* 382 */,
        null,
        null,
        0,
        "0/0/102/28",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        133,
        null,
        0,
        0,
        null,
        0x1.0800000000000p9 /* 528 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "nextFrame=145",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "void",
        null,
        null,
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.1700000000000p9 /* 558 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.0800000000000p9 /* 528 */,
        null,
        null,
        null,
        255,
        null,
        null,
        "nextFrame=145",
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        0x1.E300000000000p8 /* 483 */,
        0x1.1000000000000p7 /* 136 */,
        "gls_hollowb",
        2300,
        0,
        "void",
        null,
        "void",
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.0800000000000p9 /* 528 */,
        0x1.7E00000000000p8 /* 382 */,
        "tl_extra",
        2100,
        255,
        "0/0/102/28",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "nextFrame=145",
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294922239,
     "children" => void,
     "outline" => void,
     "uuid" => "d4bd2349-a93b-4b94-985b-b1efac854f72",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseUp",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_special",
        2000,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        122,
        0,
        1,
        "",
        null,
        0x1.2D80000000000p9 /* 603 */,
        0x1.A300000000000p8 /* 419 */,
        null,
        null,
        0,
        "0/0/123/28",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        135,
        null,
        0,
        0,
        null,
        0x1.1E80000000000p9 /* 573 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "nextFrame=197",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "void",
        null,
        null,
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.2D80000000000p9 /* 603 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.1E80000000000p9 /* 573 */,
        null,
        null,
        null,
        255,
        null,
        null,
        "nextFrame=197",
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        0x1.0200000000000p9 /* 516 */,
        0x1.0280000000000p9 /* 517 */,
        "gls_anotherbutton",
        null,
        0,
        "0/0/129/32",
        null,
        "void",
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "viewareaNo=0",
        0,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        "void",
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.1E80000000000p9 /* 573 */,
        0x1.A300000000000p8 /* 419 */,
        "tl_special",
        null,
        255,
        "0/0/123/28",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "nextFrame=197",
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4294967119,
     "children" => void,
     "outline" => void,
     "uuid" => "28e55c86-1932-4f2e-bf98-c23eb1da6718",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_entrance",
        1900,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        124,
        0,
        1,
        "",
        null,
        0x1.4500000000000p9 /* 650 */,
        0x1.C800000000000p8 /* 456 */,
        null,
        null,
        0,
        "0/0/164/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        137,
        null,
        0,
        0,
        null,
        0x1.3600000000000p9 /* 620 */,
        null,
        null,
        null,
        255,
        null,
        "void",
        "void",
        "void",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.4500000000000p9 /* 650 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.3600000000000p9 /* 620 */,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        null,
        null,
        -0x1.8000000000000p6 /* -96 */,
        0x1.6000000000000p4 /* 22 */,
        "gls_title",
        null,
        0,
        "void",
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.3600000000000p9 /* 620 */,
        0x1.C800000000000p8 /* 456 */,
        "tl_entrance",
        null,
        255,
        "0/0/164/28",
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ],
    (const) %[
     "objectSelected" => 0,
     "className" => "MenuItemObject",
     "visible" => 1,
     "lock" => void,
     "name" => "画像",
     "outlineColor" => 4283432783,
     "children" => void,
     "outline" => void,
     "uuid" => "3fdc7ccb-860a-4b09-b934-b9feae7446c9",
     "choseFrame" => void,
     "timeline" => (const) %[
      "keys" => (const) [
       "left",
       "top",
       "storage",
       "absolute",
       "opacity",
       "zoomx",
       "viewarea",
       "mouseDown",
       "mouseEnter",
       "mouseLeave",
       "keyDown",
       "itemMode"
      ],
      "length" => 223,
      "frames" => (const) [
       (const) [
        0,
        1,
        0,
        0,
        "linear",
        null,
        null,
        "tl_quit",
        1700,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        126,
        0,
        1,
        "",
        null,
        0x1.5F80000000000p9 /* 703 */,
        0x1.ED00000000000p8 /* 493 */,
        null,
        null,
        0,
        null,
        "0/0/81/32",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        139,
        null,
        0,
        0,
        null,
        0x1.5080000000000p9 /* 673 */,
        null,
        null,
        null,
        255,
        null,
        null,
        "void",
        "void",
        "void",
        "if(key==VK_DOWN&&(tmp=getMIfI(\"tl_start\"))!=void){tmp.focus();result=true;}",
        1,
        null
       ],
       (const) [
        145,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "void",
        0,
        null
       ],
       (const) [
        153,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        158,
        null,
        1,
        null,
        null,
        0x1.5F80000000000p9 /* 703 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        170,
        null,
        0,
        null,
        null,
        0x1.5080000000000p9 /* 673 */,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ],
       (const) [
        171,
        null,
        1,
        22,
        null,
        -0x1.E400000000000p6 /* -121 */,
        0x1.4800000000000p5 /* 41 */,
        "gl_bar-2",
        null,
        0,
        0x1.4000000000000p2 /* 5 */,
        "void",
        null,
        null,
        null,
        null,
        0,
        null
       ],
       (const) [
        183,
        null,
        0,
        0,
        null,
        0x1.BC00000000000p7 /* 222 */,
        null,
        null,
        null,
        255,
        0x1.0400000000000p7 /* 130 */,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        184,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        196,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        197,
        null,
        1,
        null,
        null,
        0x1.5080000000000p9 /* 673 */,
        0x1.ED00000000000p8 /* 493 */,
        "tl_quit",
        null,
        255,
        100,
        "0/0/81/32",
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        209,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        210,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        255,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       ],
       (const) [
        222,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        null
       ]
      ]
     ]
    ]
   ],
   "outline" => void,
   "uuid" => "5f081e15-cba2-4e03-b08c-aeb2d2fcb630",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
     "storage",
     "left",
     "top",
     "zoomx"
    ],
    "length" => 161,
    "frames" => (const) [
     (const) [
      0,
      0,
      0,
      0,
      "linear",
      null,
      null,
      null,
      null,
      null
     ],
     (const) [
      85,
      null,
      null,
      null,
      null,
      "tl_bg",
      0x1.C000000000000p6 /* 112 */,
      -0x1.8000000000000p3 /* -12 */,
      0x1.0068F5C28F5C3p7 /* 128.205 */,
      null
     ],
     (const) [
      171,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "BGMObject",
   "visible" => 1,
   "lock" => void,
   "name" => "BGM",
   "outlineColor" => 4283432959,
   "children" => void,
   "outline" => void,
   "uuid" => "83e113fc-999c-451c-a43c-6430a9cfbd03",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
    ],
    "length" => 161,
    "frames" => (const) [
     (const) [
      0,
      0,
      0,
      0,
      "linear",
      null
     ],
     (const) [
      171,
      null,
      null,
      null,
      null,
      null
     ]
    ]
   ]
  ],
  (const) %[
   "objectSelected" => 0,
   "className" => "MenuObject",
   "pluginName" => "menu",
   "visible" => 1,
   "lock" => void,
   "name" => "menu",
   "outlineColor" => 4283400447,
   "children" => void,
   "outline" => void,
   "uuid" => "f4dfaa6f-4bb0-4260-b856-0abc23519a9d",
   "choseFrame" => void,
   "timeline" => (const) %[
    "keys" => (const) [
    ],
    "length" => 161,
    "frames" => (const) [
     (const) [
      0,
      1,
      0,
      0,
      "linear",
      null
     ],
     (const) [
      171,
      null,
      null,
      null,
      null,
      null
     ]
    ]
   ]
  ]
 ],
 "baseHeight" => 576,
 "timelineType" => "acting",
 "currentSelectedObjectUUID" => "a32e7900-7102-4c00-9978-0f1ec49c8f02",
 "beginFrames" => (const) [
  0,
  145,
  158,
  171,
  184,
  197,
  210,
  223
 ],
 "currentAbsolute" => 2900,
 "baseWidth" => 1024,
 "frameRate" => 20
]